apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q2tkp4bcf-python
  janus-idp.io/tekton: q2tkp4bcf-python
  backstage.io/kubernetes-id: q2tkp4bcf-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q2tkp4bcf-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
