apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: q2tkp4bcf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: q2tkp4bcf-python 
  name: q2tkp4bcf-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: q2tkp4bcf-python 
